name: Build teamgram-tdesktop

on:
  push:
  workflow_dispatch: {}
  repository_dispatch:
    types: [build-desktop]

jobs:
  linux:
    name: Rocky Linux 8
    runs-on: ubuntu-latest

    strategy:
      matrix:
        defines:
          - ""
          - "DESKTOP_APP_DISABLE_X11_INTEGRATION"

    env:
      IMAGE_TAG: tdesktop:centos_env

    steps:
      - name: Clone teamgram-tdesktop
        env:
          SSH_KEY: ${{ secrets.TD_DP_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/td_dp_key
          chmod 600 ~/.ssh/td_dp_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          GIT_SSH_COMMAND="ssh -i ~/.ssh/td_dp_key -o IdentitiesOnly=yes" \
            git clone --depth 1 --recurse-submodules --shallow-submodules \
            git@github.com:Walker-00/teamgram-tdesktop.git src

      - name: First set up.
        working-directory: src
        run: |
          sudo apt update
          curl -sSL https://install.python-poetry.org | python3 -
          cd Telegram/build/docker/centos_env
          poetry install
          DOCKERFILE=$(DEBUG= LTO= poetry run gen_dockerfile)
          echo "$DOCKERFILE" > Dockerfile
          rm -rf __pycache__

      - name: Free up some disk space.
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true

      - uses: docker/setup-buildx-action@v4

      - name: Libraries cache.
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.OS }}-libs-${{ hashFiles('src/Telegram/build/docker/centos_env/**') }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Libraries.
        uses: docker/build-push-action@v7
        with:
          context: src/Telegram/build/docker/centos_env
          load: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache{-new,}

      - name: Telegram Desktop build.
        working-directory: src
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo "ARTIFACT_NAME=Telegram ${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=Telegram" >> $GITHUB_ENV
          fi

          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          -e CONFIG=Debug \
          $IMAGE_TAG \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Debug \
          -D CMAKE_C_FLAGS_DEBUG="-O0 -fuse-ld=lld" \
          -D CMAKE_CXX_FLAGS_DEBUG="-O0 -fuse-ld=lld" \
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON \
          -D TDESKTOP_API_TEST=ON \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF \
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF \
          -D TDESKTOP_REALITY_ADDRESS="${{ secrets.XIP }}" \
          -D TDESKTOP_REALITY_PORT=443 \
          -D TDESKTOP_REALITY_SERVER_NAME=hoyoverse.com \
          -D TDESKTOP_REALITY_UUID="${{ secrets.XID }}" \
          -D TDESKTOP_REALITY_PASSWORD="${{ secrets.XPASS }}" \
          -D TDESKTOP_REALITY_SHORT_ID="${{ secrets.XSID }}" \
          $DEFINE

      - name: Check.
        working-directory: src
        run: |
          filePath="out/Debug/Telegram"
          if test -f "$filePath"; then
            echo "Build successfully done!"
          else
            echo "Build error, output file does not exist."
            exit 1
          fi

      - name: Move artifact.
        working-directory: src
        run: |
          cd out/Debug
          mkdir artifact
          mv {Telegram,Updater} artifact/

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: src/out/Debug/artifact/
